version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: bewear_db
      POSTGRES_USER: bewear_user
      POSTGRES_PASSWORD: bewear_dev_password
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data